### ISSUE TITLE
Link quebradob

### ISSUE THREAD

**Issue by PedroHenriqueSantosBrasileiro** [CostelaCNX/NX-Firmwares#2]
Tentei fazer atualização e diz que o arquivo baixado não é um arquivo zip e que aconteceu provavelmente por 1 link quebrado

**Comment by caiorr1** [comment]
Tive o mesmo problema que você!
Me avise caso descubra a correção.

**Comment by atilacortez** [comment]
Aqui também ocorre o mesmo

**Comment by CostelaCNX** [comment]
Atualiza manualmente
